--Lamia AID--G2--11608696--

--TP2--
--A- Modification de contraintes


--2- Redéfinir la table en nommant les contraintes.

--SQL>
DROP TABLE ETUDIANTS CASCADE constraints;

--SQL>
CREATE TABLE ETUDIANTS
(
    NUMERO    NUMBER(4)     CONSTRAINT  TMP_NN_ETUDIANTS_NUMERO NOT NULL,
    NOM       VARCHAR2(25)  CONSTRAINT TMP_NN_ETUDIANTS_NOM NOT NULL,
    PRENOM    VARCHAR2(25)  CONSTRAINT TMP_NN_ETUDIANTS_PRENOM NOT NULL,
    SEXE      CHAR(1)       CONSTRAINT TMP_CK_ETUDIANTS_SEXE  CHECK(SEXE IN('F', 'M')),
    DATENAISSANCE DATE      CONSTRAINT  TMP_NN_ETUDIANTS_DATENAISSANCE NOT NULL,
    POIDS     NUMBER,
    ANNEE     NUMBER,
    CONSTRAINT TMP_PK_ETUDIANTS PRIMARY KEY (NUMERO)
);
